/*
 * Copyright (C) 2020 fleroviux
 *
 * Licensed under GPLv3 or any later version.
 * Refer to the included LICENSE file.
 */

#include "cpu.hpp"

void (CPU::*CPU::sOpcodeTable[256])(void) {
  // 0x0X
  /* 0xX0 */ &CPU::NOP,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Move16, OpMode::Reg16, Reg::BC, OpMode::Imm16>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::BC, OpMode::Reg, Reg::A>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Increment16, OpMode::Reg16, Reg::BC, OpMode::Reg16, Reg::BC>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Increment, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Decrement, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::Imm>,
  /* 0xX7 */ &CPU::RLCA,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::Move16, OpMode::Pointer16Word, Reg::None, OpMode::Reg16, Reg::SP>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Add16, OpMode::Reg16, Reg::HL, OpMode::Reg16, Reg::BC>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::BC>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Decrement16, OpMode::Reg16, Reg::BC, OpMode::Reg16, Reg::BC>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Increment, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Decrement, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::Imm>,
  /* 0xXF */ &CPU::RRCA,

  // 0x1X
  /* 0xX0 */ &CPU::NOP, // STOP
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Move16, OpMode::Reg16, Reg::DE, OpMode::Imm16>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::DE, OpMode::Reg, Reg::A>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Increment16, OpMode::Reg16, Reg::DE, OpMode::Reg16, Reg::DE>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Increment, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Decrement, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::Imm>,
  /* 0xX7 */ &CPU::RLA,
  /* 0xX8 */ &CPU::JR_S8,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Add16, OpMode::Reg16, Reg::HL, OpMode::Reg16, Reg::DE>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::DE>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Decrement16, OpMode::Reg16, Reg::DE, OpMode::Reg16, Reg::DE>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Increment, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Decrement, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::Imm>,
  /* 0xXF */ &CPU::RRA,

  // 0x2X
  /* 0xX0 */ &CPU::JR_COND_S8<Flag::Zero, false>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Move16, OpMode::Reg16, Reg::HL, OpMode::Imm16>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16Inc, Reg::HL, OpMode::Reg, Reg::A>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Increment16, OpMode::Reg16, Reg::HL, OpMode::Reg16, Reg::HL>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Increment, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Decrement, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::Imm>,
  /* 0xX7 */ &CPU::DAA,
  /* 0xX8 */ &CPU::JR_COND_S8<Flag::Zero, true>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Add16, OpMode::Reg16, Reg::HL, OpMode::Reg16, Reg::HL>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::PointerReg16Inc, Reg::HL>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Decrement16, OpMode::Reg16, Reg::HL, OpMode::Reg16, Reg::HL>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Increment, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Decrement, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::Imm>,
  /* 0xXF */ &CPU::CPL,

  // 0x3X
  /* 0xX0 */ &CPU::JR_COND_S8<Flag::Carry, false>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Move16, OpMode::Reg16, Reg::SP, OpMode::Imm16>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16Dec, Reg::HL, OpMode::Reg, Reg::A>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Increment16, OpMode::Reg16, Reg::SP, OpMode::Reg16, Reg::SP>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Increment, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Decrement, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::HL, OpMode::Imm>,
  /* 0xX7 */ &CPU::SCF,
  /* 0xX8 */ &CPU::JR_COND_S8<Flag::Carry, true>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Add16, OpMode::Reg16, Reg::HL, OpMode::Reg16, Reg::SP>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::PointerReg16Dec, Reg::HL>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Decrement16, OpMode::Reg16, Reg::SP, OpMode::Reg16, Reg::SP>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Increment, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Decrement, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xXF */ &CPU::CCF,

  // 0x4X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::B, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::C, OpMode::Reg, Reg::A>,

  // 0x5X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::D, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::E, OpMode::Reg, Reg::A>,

  // 0x6X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::H, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::L, OpMode::Reg, Reg::A>,

  // 0x7X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::HL, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::HL, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::HL, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::HL, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::HL, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::HL, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::HALT,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerReg16, Reg::HL, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0x8X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0x9X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0xAX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0xBX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0xCX
  /* 0xX0 */ &CPU::RET_COND<Flag::Zero, false>,
  /* 0xX1 */ &CPU::POP_R16<RegW::BC>,
  /* 0xX2 */ &CPU::JP_COND_U16<Flag::Zero, false>,
  /* 0xX3 */ &CPU::JP_U16,
  /* 0xX4 */ &CPU::CALL_COND_U16<Flag::Zero, false>,
  /* 0xX5 */ &CPU::PUSH_R16<RegW::BC>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Add, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xX7 */ &CPU::RST<0x00>,
  /* 0xX8 */ &CPU::RET_COND<Flag::Zero, true>,
  /* 0xX9 */ &CPU::RET,
  /* 0xXA */ &CPU::JP_COND_U16<Flag::Zero, true>,
  /* 0xXB */ &CPU::PREFIX_CB,
  /* 0xXC */ &CPU::CALL_COND_U16<Flag::Zero, true>,
  /* 0xXD */ &CPU::CALL_U16,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::AddWithCarry, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xXF */ &CPU::RST<0x08>,

  // 0xDX
  /* 0xX0 */ &CPU::RET_COND<Flag::Carry, false>,
  /* 0xX1 */ &CPU::POP_R16<RegW::DE>,
  /* 0xX2 */ &CPU::JP_COND_U16<Flag::Carry, false>,
  /* 0xX3 */ &CPU::UNKNOWN, // unused opcode
  /* 0xX4 */ &CPU::CALL_COND_U16<Flag::Carry, false>,
  /* 0xX5 */ &CPU::PUSH_R16<RegW::DE>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::Sub, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xX7 */ &CPU::RST<0x10>,
  /* 0xX8 */ &CPU::RET_COND<Flag::Carry, true>,
  /* 0xX9 */ &CPU::RETI,
  /* 0xXA */ &CPU::JP_COND_U16<Flag::Carry, true>,
  /* 0xXB */ &CPU::UNKNOWN, // unused opcode
  /* 0xXC */ &CPU::CALL_COND_U16<Flag::Carry, true>,
  /* 0xXD */ &CPU::UNKNOWN, // unused opcode
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::SubWithCarry, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xXF */ &CPU::RST<0x18>,

  // 0xEX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::HighMemImm, Reg::None, OpMode::Reg, Reg::A>,
  /* 0xX1 */ &CPU::POP_R16<RegW::HL>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::HighMemC, Reg::None, OpMode::Reg, Reg::A>,
  /* 0xX3 */ &CPU::UNKNOWN, // unused opcode
  /* 0xX4 */ &CPU::UNKNOWN, // unused opcode
  /* 0xX5 */ &CPU::PUSH_R16<RegW::HL>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::AND, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xX7 */ &CPU::RST<0x20>,
  /* 0xX8 */ &CPU::ADD_SP_S8,
  /* 0xX9 */ &CPU::JP_HL,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::PointerWord, Reg::None, OpMode::Reg, Reg::A>,
  /* 0xXB */ &CPU::UNKNOWN, // unused opcode
  /* 0xXC */ &CPU::UNKNOWN, // unused opcode
  /* 0xXD */ &CPU::UNKNOWN, // unused opcode
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::XOR, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xXF */ &CPU::RST<0x28>,

  // 0xFX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::HighMemImm>,
  /* 0xX1 */ &CPU::POP_R16<RegW::AF>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::HighMemC>,
  /* 0xX3 */ &CPU::DI,
  /* 0xX4 */ &CPU::UNKNOWN, // unused opcode
  /* 0xX5 */ &CPU::PUSH_R16<RegW::AF>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::OR, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xX7 */ &CPU::RST<0x30>,
  /* 0xX8 */ &CPU::LD_HL_SP_S8,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::Move16, OpMode::Reg16, Reg::SP, OpMode::Reg16, Reg::HL>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::Move, OpMode::Reg, Reg::A, OpMode::PointerWord>,
  /* 0xXB */ &CPU::EI,
  /* 0xXC */ &CPU::UNKNOWN, // unused opcode
  /* 0xXD */ &CPU::UNKNOWN, // unused opcode
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::Compare, OpMode::Reg, Reg::A, OpMode::Imm>,
  /* 0xXF */ &CPU::RST<0x38>
};

void (CPU::*CPU::sOpcodeTableCB[256])(void) {
  // 0x0X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::RLC, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::RLC, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::RLC, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::RLC, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::RLC, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::RLC, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::RLC, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::RLC, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::RRC, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::RRC, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::RRC, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::RRC, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::RRC, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::RRC, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::RRC, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::RRC, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0x1X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::RL, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::RL, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::RL, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::RL, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::RL, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::RL, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::RL, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::RL, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::RR, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::RR, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::RR, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::RR, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::RR, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::RR, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::RR, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::RR, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0x2X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::SLA, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::SLA, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::SLA, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::SLA, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::SLA, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::SLA, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::SLA, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::SLA, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::SRA, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::SRA, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::SRA, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::SRA, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::SRA, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::SRA, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::SRA, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::SRA, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0x3X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::SWAP, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::SWAP, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::SWAP, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::SWAP, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::SWAP, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::SWAP, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::SWAP, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::SWAP, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::SRL, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::SRL, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::SRL, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::SRL, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::SRL, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::SRL, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::SRL, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::SRL, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A>,

  // 0x4X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 0>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 0>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 0>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 0>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 0>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 0>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 0>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 0>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 1>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 1>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 1>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 1>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 1>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 1>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 1>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 1>,

  // 0x5X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 2>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 2>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 2>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 2>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 2>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 2>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 2>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 2>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 3>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 3>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 3>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 3>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 3>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 3>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 3>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 3>,

  // 0x6X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 4>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 4>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 4>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 4>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 4>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 4>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 4>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 4>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 5>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 5>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 5>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 5>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 5>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 5>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 5>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 5>,

  // 0x7X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 6>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 6>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 6>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 6>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 6>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 6>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 6>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 6>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 7>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 7>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 7>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 7>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 7>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 7>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 7>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::BIT, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 7>,

  // 0x8X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 0>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 0>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 0>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 0>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 0>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 0>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 0>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 0>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 1>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 1>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 1>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 1>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 1>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 1>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 1>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 1>,

  // 0x9X
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 2>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 2>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 2>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 2>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 2>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 2>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 2>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 2>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 3>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 3>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 3>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 3>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 3>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 3>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 3>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 3>,

  // 0xAX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 4>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 4>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 4>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 4>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 4>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 4>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 4>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 4>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 5>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 5>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 5>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 5>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 5>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 5>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 5>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 5>,

  // 0xBX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 6>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 6>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 6>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 6>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 6>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 6>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 6>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 6>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 7>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 7>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 7>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 7>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 7>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 7>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 7>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::RES, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 7>,

  // 0xCX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 0>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 0>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 0>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 0>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 0>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 0>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 0>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 0>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 1>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 1>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 1>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 1>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 1>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 1>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 1>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 1>,

  // 0xDX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 2>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 2>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 2>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 2>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 2>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 2>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 2>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 2>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 3>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 3>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 3>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 3>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 3>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 3>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 3>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 3>,

  // 0xEX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 4>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 4>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 4>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 4>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 4>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 4>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 4>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 4>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 5>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 5>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 5>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 5>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 5>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 5>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 5>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 5>,

  // 0xFX
  /* 0xX0 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 6>,
  /* 0xX1 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 6>,
  /* 0xX2 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 6>,
  /* 0xX3 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 6>,
  /* 0xX4 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 6>,
  /* 0xX5 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 6>,
  /* 0xX6 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 6>,
  /* 0xX7 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 6>,
  /* 0xX8 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::B, OpMode::Reg, Reg::B, 7>,
  /* 0xX9 */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::C, OpMode::Reg, Reg::C, 7>,
  /* 0xXA */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::D, OpMode::Reg, Reg::D, 7>,
  /* 0xXB */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::E, OpMode::Reg, Reg::E, 7>,
  /* 0xXC */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::H, OpMode::Reg, Reg::H, 7>,
  /* 0xXD */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::L, OpMode::Reg, Reg::L, 7>,
  /* 0xXE */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::PointerReg16, Reg::HL, OpMode::PointerReg16, Reg::HL, 7>,
  /* 0xXF */ &CPU::GenerateOpcode<GenericOp::SET, OpMode::Reg, Reg::A, OpMode::Reg, Reg::A, 7>,
};